# Generated by Django 5.1 on 2024-08-16 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=250)),
                ('phone', models.TextField()),
                ('address', models.TextField()),
                ('serviceType', models.TextField()),
                ('serviceFrequency', models.TextField()),
                ('pickupDate', models.DateField()),
                ('pickupTime', models.TimeField()),
                ('wasteType', models.TextField()),
                ('wasteVolume', models.FloatField()),
                ('emergencyContact', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
